container:
  image: node:buster

lodash_task:
  env:
    VERSION: 4.17.20
  get_npm_package_script:
    - wget $(npm view lodash@$VERSION dist.tarball)
    - tar xf lodash-$VERSION.tgz --strip-components=1 --one-top-level=npm-package
  build_our_package_script:
    - git clone --depth 1 --branch $VERSION-npm https://github.com/lodash/lodash.git
    - npm pack ./lodash
    - tar xf lodash-$VERSION.tgz --strip-components=1 --one-top-level=our-package
  diff_directories_script:
    - diff -r npm-package our-package

chalk_task:
  env:
    VERSION: 4.1.0
  get_npm_package_script:
    - wget $(npm view chalk@$VERSION dist.tarball)
    - tar xf chalk-$VERSION.tgz --strip-components=1 --one-top-level=npm-package
  build_our_package_script:
    - git clone --depth 1 --branch v$VERSION https://github.com/chalk/chalk.git
    - npm pack ./chalk
    - tar xf chalk-$VERSION.tgz --strip-components=1 --one-top-level=our-package
  diff_directories_script:
    - diff -r npm-package our-package

tslib_task:
  env:
    VERSION: 2.1.0
  get_npm_package_script:
    - wget $(npm view tslib@$VERSION dist.tarball)
    - tar xf tslib-$VERSION.tgz --strip-components=1 --one-top-level=npm-package
  build_our_package_script:
    - git clone --depth 1 --branch $VERSION https://github.com/Microsoft/tslib.git
    - npm pack ./tslib
    - tar xf tslib-$VERSION.tgz --strip-components=1 --one-top-level=our-package
  diff_directories_script:
    - diff -r npm-package our-package
