container:
  image: node:buster

lodash_task:
  env:
    VERSION: 4.17.20
  get_npm_package_script:
    - wget $(npm view lodash@$VERSION dist.tarball)
    - tar xf lodash-$VERSION.tgz --strip-components=1 --one-top-level=npm-package
  build_our_package_script:
    - git clone --depth 1 --branch $VERSION-npm https://github.com/lodash/lodash.git
    - npm pack ./lodash
    - tar xf lodash-$VERSION.tgz --strip-components=1 --one-top-level=our-package
  diff_directories_script:
    - diff -r npm-package our-package
